version: '3.4'

services:
  db:
    #    container_name: postgresql
    restart: always
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD=Dominim123_!
      - POSTGRES_USER=admin
    #    volumes:
    #      - ./api/docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - target: 5432
        published: 5432
        
        
  php:
    #    container_name: php
    restart: always
    build:
      context: ./api
      target: api_platform_php
    depends_on:
      - db
  #      - dev-tls
  #    volumes:
  #      - ./api:/srv/api:rw,cached
  #      - ./api/docker/php/conf.d/api-platform.dev.ini:/usr/local/etc/php/conf.d/api-platform.ini
  #      - dev-certs:/certs:ro,nocopy

  api:
    #    container_name: api
    build:
      context: ./api
      target: api_platform_nginx
    depends_on:
      - php
    ports:
      - target: 80
        published: 80

        #    volumes:
        #      - ./api/public:/srv/api/public:ro
        
        

  client:
    build:
      context: ./client
      target: api_platform_client_nginx
    ports:
    - 3001:80

  app:
    build:
      context: ./app
      target: api_platform_app_nginx
#    tty: true # https://github.com/facebook/create-react-app/issues/8688
    ports:
      - 3002:80

#  dev-tls:
#    container_name: START
#    build:
#      context: ./docker/dev-tls
#    volumes:
#      - dev-certs:/certs:rw
#    ports:
#      - target: 80
#        published: 80
#        protocol: tcp

#volumes:
#  db-data: {}
#  dev-certs: {}


  #  vulcain:
  #    container_name: vulcain
  #    image: dunglas/vulcain
  #    environment:
  #      - CERT_FILE=/certs/localhost.crt
  #      - KEY_FILE=/certs/localhost.key
  #      - UPSTREAM=http://api
  #    depends_on:
  #      - api
  #      - dev-tls
  #    volumes:
  #      - dev-certs:/certs:ro,nocopy
  #    ports:
  #      - target: 443
  #        published: 8443
  #        protocol: tcp


#  mercure:
#    container_name: mercure
#    image: dunglas/mercure
#    environment:
#      - ALLOW_ANONYMOUS=1
#      - CERT_FILE=/certs/localhost.crt
#      - CORS_ALLOWED_ORIGINS=*
#      - DEMO=1
#      - JWT_KEY=Dominim123_!
#      - KEY_FILE=/certs/localhost.key
#      - PUBLISH_ALLOWED_ORIGINS=https://localhost:1337 
#    depends_on:
#      - dev-tls
#    volumes:
#      - dev-certs:/certs:ro,nocopy
#    ports:
#      - target: 443
#        published: 1337
#        protocol: tcp
