security:
    enable_authenticator_manager: true
    encoders:
        Symfony\Component\Security\Core\User\User: 'auto'

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        backend_users:
            memory:
                users:
                    admin: { password: '$argon2id$v=19$m=65536,t=4,p=1$iKmY1lZBtop3dmYN9/bl4g$Z3dBZLGkmemOAkKcolyEpiBNtTOgqnCvlZwlD7J65vg' , 
                             roles: ['ROLE_ADMIN'] }
                    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: backend_users
            entry_point: form_login
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
                target: app_login


    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN, requires_channel: https}
        # - { path: ^/profile, roles: ROLE_USER }
