version: '3.4'

services:
  php:
    image: docker.io/qvllasa/homepage:php
    restart: always
    depends_on:
      - db
    environment:
      - APP_DEBUG=0
      - APP_ENV=prod
      - APP_SECRET=Dominim123_!
#      - CORS_ALLOW_ORIGIN=^https://(?:\w+\.)?qendrimvllasa\.com$
      - DATABASE_URL=postgres://admin:Dominim123_!@db/api
      - MERCURE_JWT_SECRET=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InN1YnNjcmliZSI6WyJmb28iLCJiYXIiXSwicHVibGlzaCI6WyJmb28iXX19.B0MuTRMPLrut4Nt3wxVvLtfWB_y189VEpWMlSmIQABQ
      - MERCURE_SUBSCRIBE_URL=https://mercure.qendrimvllasa.com/hub
#      - TRUSTED_HOSTS=^(?:localhost|api|api\.qendrimvllasa\.com)$
      - TRUSTED_PROXIES=${TRUSTED_PROXIES:-10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}

  api:
    image: docker.io/qvllasa/homepage:nginx
    restart: always
    depends_on:
      - php

  cache-proxy:
    image: docker.io/qvllasa/homepage:varnish
    restart: always
    depends_on:
      - api
    environment:
      - VIRTUAL_HOST=api.qendrimvllasa.com,www.api.qendrimvllasa.com
    tmpfs:
      - /usr/local/var/varnish:exec

  db:
    # in production, we may want to use a managed database service
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD=Dominim123_!
      - POSTGRES_USER=admin
    volumes:
      # use a bind-mounted host directory, because we never want to lose our data!
      - ../api/docker/db/data:/var/lib/postgresql/data:rw

  mercure:
    # in production, we may want to use the managed version of Mercure
    # https://mercure.rocks/pricing
    image: dunglas/mercure
    restart: always
    environment:
      - ALLOW_ANONYMOUS=0
      - CORS_ALLOWED_ORIGINS=https://qendrimvllasa.com,https://admin.qendrimvllasa.com
      - JWT_KEY=4121344212538417de3e2118
      - VIRTUAL_HOST=mercure.example.com

  client:
    # in production, we may want to use a static website hosting service
    # https://facebook.github.io/create-react-app/docs/deployment
    image: ${CLIENT_IMAGE:?CLIENT_IMAGE is not set or empty}
    restart: always
    environment:
      - VIRTUAL_HOST=platform.qendrimvllasa.com,www.platform.qendrimvllasa.com

  app:
    # in production, we may want to use a static website hosting service
    # https://facebook.github.io/create-react-app/docs/deployment
    image: docker.io/qvllasa/homepage:app
    restart: always
    environment:
      - VIRTUAL_HOST=qendrimvllasa.com,www.qendrimvllasa.com

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
#      - ./docker/nginx-proxy/certs:/etc/nginx/certs:ro
      - ./docker/nginx-proxy/vhost.d:/etc/nginx/vhost.d:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
